### PR TITLE
`release/v0` update

### PR DESCRIPTION
**Pull request by tarakby**
- port changes from https://github.com/onflow/flow-emulator/blob/tarak/v0.58.1-0-with-crypto-type-fixes
- upgrade flow-go and flow-go-sdk versions

### CODE REVIEW

**Review by peterargue — APPROVED** [review]

**Comment by tarakby** [comment]
@chasefleming if you're fine with upgrading `flow-go` (latest on master) and `flow-go-sdk` (v0.44), then feel free to merge this PR

**Comment by chasefleming** [comment]
@tarakby the Go SDK is at `v0.45.0` now. Can you upgrade to that please? Also, I think there is a later release of `flow-go` now.

**Comment by sideninja** [comment]
@chasefleming sorry for ignoring your comment, will make another PR addressing that. I just overlooked it

**Comment by tarakby** [comment]
The version of `flow-go` I used is the latest commit on `master` as of yesterday, so it's more recent than the releases/tags

**Pull request merged**
