### PR TITLE
[EVM] Update Flow Go v0.34.0-crescendo-preview.16 

### PR DESCRIPTION
**Pull request by sideninja**
Depends on https://github.com/onflow/flow-go/pull/5792

Updates to the latest tag of flow-go feature/cadence branch [v0.34.0-crescendo-preview.16](https://github.com/onflow/flow-go/releases/tag/v0.34.0-crescendo-preview.16)

### CODE REVIEW

**Comment by turbolent** [comment]
It doesn't look like this refers to a recent commit of https://github.com/onflow/flow-go/commits/feature/stable-cadence. Maybe it's the wrong commit?

**Comment by turbolent** [comment]
> Because I still couldn't get PRs in due to CI issues.

Sorry, maybe I should have asked differently: The PR title says "update to latest version", what is it updating to? The commit doesn't seem to be a recent commit of `feature/stable-cadence`. Is this a recent commit of flow-go master? In that case it should target `v0/release`

**Comment by sideninja** [comment]
> > Because I still couldn't get PRs in due to CI issues.
> 
> Sorry, maybe I should have asked differently: The PR title says "update to latest version", what is it updating to? The commit doesn't seem to be a recent commit of `feature/stable-cadence`. Is this a recent commit of flow-go master? In that case it should target `v0/release`

I should leave it in a draft. I plan to update the version to a tagged version of flow-go once the PRs get merged. What it will target will be the feature/cadence branch's latest tag (the one created after PRs are in) and I will also update the description accordingly. This is just a dirty branch now that targets specific commits so I'm not blocked completely waiting for that PR to get in.

**Comment by turbolent** [comment]
Looks like `1640cba0aa74` comes from https://github.com/onflow/flow-go/pull/5792. 

I updated/finished https://github.com/onflow/flow-go/pull/5792 and once that's merged in, we can update this PR  to the latest commit of flow-go's feature/stable-cadence.

**Comment by sideninja** [comment]
> Looks like `1640cba0aa74` comes from [onflow/flow-go#5792](https://github.com/onflow/flow-go/pull/5792).
> 
> I updated/finished [onflow/flow-go#5792](https://github.com/onflow/flow-go/pull/5792) and once that's merged in, we can update this PR to the latest commit of flow-go's feature/stable-cadence.

That was the plan yes

**Comment by sideninja** [comment]
@turbolent it's ready now.

**Comment by turbolent** [comment]
@sideninja I'm still a bit confused here: This PR updates to flow-go `v0.34.0-crescendo-preview.16`, but that tag does not exist: https://github.com/onflow/flow-go/tree/v0.34.0-crescendo-preview.16 🤔

**Pull request merged**
