### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by psiemens**
Taking myself off here since I'm no longer an active maintainer 😄

### CODE REVIEW

**Comment by turbolent** [comment]
End of an era, Peter started the Emulator and we wouldn't be here without it!

Thank you so much for all your hard and amazing work Peter!

**Review by sideninja — APPROVED** [review]
Thank you for all the work! your ingenuity will be missed, but then again I'm sure we will see you lurking around :D

**Comment by bluesign** [comment]
I learned a lot of from emulator codebase, thanks a lot @psiemens ❤️

**Comment by psiemens** [comment]
Thanks everybody! I'm always happy to contribute and help with reviews. I just didn't want to be a blocker on future PRs. Thanks for all the improvements you've made to the codebase since we started it!

**Pull request merged**
