### PR TITLE
[Access] SubscribeBlocks endpoint is missing

### PR DESCRIPTION
**Pull request by UlyanaAndrukhiv**
FLIP: https://github.com/onflow/flips/pull/229

## Description

This pull request :
- implements missing `SubscribeBlocks`, `SubscribeBlockHeaders` and `SubscribeBlockDigests` methods from Access API interface
- updates `RegisterAccessAPIServer`, `StateStreamBackend` and creating `backend.Config` according to new `flow-go` package version
- resolves dependencies (removed flow-archive dependency & storage/remote package) according to PR  [#524]
- fixed tests (according to [comment](https://github.com/onflow/flow-emulator/pull/524#issuecomment-1841497348))

______

### CODE REVIEW

**Comment by turbolent** [comment]
Nice! Is this also going to be ported to master?

**Comment by UlyanaAndrukhiv** [comment]
Hi, @tarakby, 
 I observed that you recently you had cleaned up the replace statements in `flow-go` `./integration` and `flow-go` still uses the untagged version of flow-emulator from  [tarak/v0.58.1-0-with-crypto-type-fixes](https://github.com/onflow/flow-emulator/tree/tarak/v0.58.1-0-with-crypto-type-fixes) branch. To address this, I have prepared this PR that includes the necessary changes to this [tarak/v0.58.1-0-with-crypto-type-fixes](https://github.com/onflow/flow-emulator/tree/tarak/v0.58.1-0-with-crypto-type-fixes) branch.

**Comment by tarakby** [comment]
Hi @UlyanaAndrukhiv,  thanks for the ping! Yes you are right, this non tagged branch is used by `flow-go` because it still uses Cadence prior to `1.0`. Importing `flow-emulator` master or other recent tags causes Cadence `1.0` to be imported in `flow-go` which is not possible yet.
I agree with the idea to extend my branch, though am not maintaining the `flow-emulator` repo and don't know the context of your changes. I therefore let the other people review the changes and approve. 

I also think your changes could be backported into master so they don't get lost once we're done with my branch.

**Comment by turbolent** [comment]
So flow-go `master` uses Emulator's [tarak/v0.58.1-0-with-crypto-type-fixes](https://github.com/onflow/flow-emulator/tree/tarak/v0.58.1-0-with-crypto-type-fixes?rgh-link-date=2024-02-07T17%3A03%3A13Z) branch (https://github.com/onflow/flow-go/blob/master/integration/go.mod#L26).

The name of that branch looks like a temporary name. Maybe the Emulator repo should have a dedicated `cadence-0.42` branch?

**Comment by turbolent** [comment]
cc @sideninja: This is one of the solutions I had mentioned re: EVM. Once we have this branch, maybe EVM related PRs that are already on `master`, like #515, can be backported, and that would unblock the EVM + Cadence v0.42 work?

**Comment by UlyanaAndrukhiv** [comment]
@sideninja, what are your thoughts on the discussion upper? Thank you in advance.

**Comment by sideninja** [comment]
We should create a branch like @turbolent suggested that is pre-cadence 1.0. As a source branch, the Taraks' branch can be used. Then if there's something that is needed to unblock we can backport changes. However I think that for the purpose of flow-go EVM work it's better to use the updated feature/cadence branch since anyhow we are preparing for Crescendo. 

@UlyanaAndrukhiv if you want you can create that yourself but if you need help or want me to create the base branch let me know.

**Comment by chasefleming** [comment]
Heads up, I have created a branch off of `v0.59.0` called `release/v0` for #566 . This is so we can continue releasing before `v.1.0.0`. If you need something to go out before v1 this would be the branch to do it off of from here on out. Note that anything merged to this branch will also need to be cherry picked to master. cc @turbolent

**Comment by UlyanaAndrukhiv** [comment]
I recreated a new PR https://github.com/onflow/flow-emulator/pull/593 that targets the release/v0 branch

**Pull request closed without merging**
