### PR TITLE
Do not depend on RegisterID.String()

### PR DESCRIPTION
**Pull request by SaveTheRbtz**
Closes #???

## Description

This method may be removed in the future[1], so let's future-proof the emulator.

[1] https://github.com/onflow/flow-go/pull/3529 

______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to GitHub issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-emulator/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Review by sideninja — APPROVED** [review]
LGTM

**Comment by bluesign** [comment]
Maybe off-topic, but why would someone remove `Stringer`? Is it some cargo cult?

**Review by turbolent — APPROVED** [review]

**Comment by SaveTheRbtz** [comment]
> Maybe off-topic (and no offense intended), but why would someone remove `Stringer`? Is it some cargo cult or has some real benefit?

I would re-phrase it a bit differently: why does one add a stringer to a simple struct?  IMHO, a struct does not need a canonical string representation.

PS. This specific one was used as a hack for map indexing and would be removed.

**Comment by bluesign** [comment]
> I would re-phrase it a bit differently: why does one add a stringer to a simple struct? IMHO, a struct does not need a canonical string representation.

Probably my bad, I thought it is a bit go etiquette to provide Stringer to public structs. Though my go knowledge is limited to reading mostly stdlib code. [0]


https://cs.opensource.google/go/go/+/refs/tags/go1.19.3:src/net/unixsock.go;l=22

**Pull request merged**
