### PR TITLE
Update cadence version

### PR DESCRIPTION
**Pull request by SupunS**
## Description

Update to the cadence version which includes the dependency fix: https://github.com/onflow/cadence/pull/3027

______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to GitHub issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-emulator/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation
- [x] Re-reviewed `Files changed` in the GitHub PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by tarakby** [comment]
@SupunS are the contracts (core-contrcats, nft, ft) currently being updated ? Are there PRs I should track about the updates? This is to unblock an emulator PR similar to yours :)

**Comment by SupunS** [comment]
@tarakby Josh is working on updating the contracts. There is a PR to update flow-go with the latest changes: https://github.com/onflow/flow-go/pull/5301. Not sure if that will fix this issue for sure, but once that PR got merged, I will update this PR and see.

**Review by dsainati1 — APPROVED** [review]
Thank you! This should unblock https://github.com/onflow/flow-emulator/pull/553

**Review by turbolent — APPROVED** [review]
👏

**Comment by tarakby** [comment]
Nice work 👏🏼

**Pull request merged**
