### PR TITLE
[Access] Get Block endpoint is missing the system collection

### PR DESCRIPTION
**Pull request by AndriiDiachuk**
https://github.com/onflow/flow-go/issues/4584

This pull request implements two missing methods `GetSystemTransaction`, `GetSystemTransactionResult` from Access API interface.

### CODE REVIEW

**Review by sideninja — CHANGES_REQUESTED** [review]
Let's wait for that PR to get merged

**Comment by jordanschalm** [comment]
> Let's wait for that PR to get merged

As far as I can tell, this change is backward-compatible on the `flow-emulator` side and not backward-compatible on the `flow-go` side. In these cases, would it not make sense to merge the `flow-emulator` PR first?

**Comment by AndriiDiachuk** [comment]
> Let's wait for that PR to get merged

@sideninja  Could you please merge than, as I need those changes for https://github.com/onflow/flow-go/pull/5049. As @jordanschalm mentioned I can't merge `flow-go` PR first.

**Comment by sideninja** [comment]
which PR do you need to be merged? what is the reason for targeting your forked flow-go?

**Comment by AndriiDiachuk** [comment]
> which PR do you need to be merged? what is the reason for targeting your forked flow-go?

I need to merge flow-emulator PR(https://github.com/onflow/flow-emulator/pull/514) first, so jobs in PR(https://github.com/onflow/flow-go/pull/5049) won't fail and guys from the team will be able to merge my PR in master without `replace` statement there.

**Comment by sideninja** [comment]
Looks like the PR you linked is already merged?

**Comment by sideninja** [comment]
But I agree that shouldn't have a replace directive there, so it's better to have it here temporarily. Let's get this merged targeting flow-go master and then do a follow-up PR on flow-go removing the replace directive.

**Comment by AndriiDiachuk** [comment]
> Looks like the PR you linked is already merged?

It was reverted because of `replace` statement.

**Comment by AndriiDiachuk** [comment]
> But I agree that shouldn't have a replace directive there, so it's better to have it here temporarily. Let's get this merged targeting flow-go master and then do a follow-up PR on flow-go removing the replace directive.

Yes, that was the idea. Remove it from `flow-emulator` after merging on `flow-go`. I will remove `replace` from here right after it will be merged in `master` on `flow-go`. Thanks for understanding.

**Comment by AndriiDiachuk** [comment]
> Let's wait for that PR to get merged

Could you please merge this PR for now, so I can finish with the corresponding PR in `flow-go`.

**Comment by sideninja** [comment]
> > Looks like the PR you linked is already merged?
> 
> It was reverted because of `replace` statement.

Ahh missed this message. Ok makes sense.

**Review by sideninja — APPROVED** [review]

**Comment by sideninja** [comment]
@AndriiDiachuk can you please update your flow-go forked version you replace here and make another PR for that since you are now blocking some other features relying on latest flow-go master

**Comment by AndriiDiachuk** [comment]
> @AndriiDiachuk can you please update your flow-go forked version you replace here and make another PR for that since you are now blocking some other features relying on latest flow-go master

Thanks for help with merging. Here is the new PR(https://github.com/onflow/flow-go/pull/5078) for the flow-go without `replace` statement. Once it will be merged, I will create new PR for the flow-emulator to remove `replace` statement here as well.

**Pull request merged**
