### PR TITLE
Add OnStart callback for emulator start

### LINKED ISSUE #565: Allow a callback to be trigger after emulator has started
### Issue To Be Solved

We need a way in other projects, like the CLI, to know when the emulator has started.

### (Optional): Suggest A Solution

Introduce a variadic options arg (for non-breaking changes) that takes an options struct with a callback to be triggered once the emulator has completed.

### PR DESCRIPTION
**Pull request by chasefleming**
Closes #565 

______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to GitHub issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-emulator/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [x] Re-reviewed `Files changed` in the GitHub PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by turbolent** [comment]
Nice! What is the `release/v0` branch?

**Comment by chasefleming** [comment]
@turbolent we need a way to still release non v1 features now that everything has been merged to master. I cut this branch so have the ability to do more releases like v0.60.0 if we need a change in the meantime. This means we'll have to cherry pick everything we do over here into a PR for the master branch as well. Don't foresee many changes though.

**Comment by turbolent** [comment]
Sounds good! 👍 There's a discussion about having such a branch in #564, maybe good to coordinate and document it, so we don't end up with multiple different ones

**Comment by chasefleming** [comment]
Thanks for the heads up @turbolent . Left a comment on there.

**Comment by bluesign** [comment]
@chasefleming is this works? afaik start call is blocking (library we used there, graceland is blocking actually) 

I think emulator should start after the start call anyway, what was the issue there?

**Comment by chasefleming** [comment]
@bluesign you're right. I need to rethink my approach. Moving this to a draft PR. Sorry, what do you mean by "start after start call." If `start` blocks, what I am trying to do is figure out a way to notify whatever called it that you can continue on a next step. e.g. deploy a contract to the emulator.

**Comment by bluesign** [comment]
@chasefleming who is the caller here? who is starting emulator I mean. I think if you call Listen before Start, emulator should be ready anyway, os will make socket wait till it is handled.

**Comment by chasefleming** [comment]
@bluesign In one use case, the CLI is the caller. I tried this, but unless I put a sleep to delay it the following code fails because it's not actually ready:

```go
emuErr := emulatorServer.Listen()
if emuErr != nil {
	// TODO: handle error
}

go func() {
	emulatorServer.Start()
}()
fmt.Println("Emulator server is ready")
```

Any ideas or see anything I'm doing wrong?

**Comment by chasefleming** [comment]
This is addressed by this: https://github.com/onflow/flow-go-sdk/pull/578

**Pull request closed without merging**
