### PR TITLE
Retire storage api

### LINKED ISSUE #243: Refactor account storage inspection
Refactor account storage inspection to start using Cadence script to iterate over account storage and return the data https://developers.flow.com/cadence/language/accounts

Although we should discuss whether we should keep the implementation for private storage since that isn't exposed with Cadence Account methods.

### PR DESCRIPTION
**Pull request by bluesign**
Closes #243 

## Description

Opened as draft, we can merge later when we want. 

______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to GitHub issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-emulator/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [x] Re-reviewed `Files changed` in the GitHub PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Review by sideninja — COMMENTED** [review]
We should remove also the methods on the backend and the types defined there.

**Comment by bluesign** [comment]
@sideninja should we wait reorg to be merged? otherwise will be rebase probably.

**Comment by sideninja** [comment]
> 

As you wish. I'm fine with whatever is easier for you, but it should remove other things as mentioned.

**Comment by sideninja** [comment]
@bluesign if you can just remove the other related part and we get this merged.

**Pull request closed without merging**
