### PR TITLE
backend reorg try - do not merge

### PR DESCRIPTION
**Pull request by bluesign**
Closes #???

## Description

@sideninja this is the changes I mentioned 
______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to GitHub issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-emulator/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Comment by bluesign** [comment]
Btw this is a pretty big change and reorg than I anticipated, we can also skip

**Comment by sideninja** [comment]
Let me go through it, I think addressing this is good, just need to understand the consequences first.

**Comment by sideninja** [comment]
@bluesign let me respond on Monday. Sorry.

**Comment by bluesign** [comment]
@sideninja no problem at all, it is big change, take your time.

**Comment by sideninja** [comment]
@bluesign I agree with this approach. 

I would just restructure the backend part, I would just rename `backend` package to `adapters` and then change the `adapter.go` to `access.go` and `backend.go` to `sdk.go` since they each adapt the responses to match the access API spec and the other to SDK.  

I will give it a more detailed pass in the future when you finish it, but architecturally speaking I would say this is an improvement.

**Comment by sideninja** [comment]
> @sideninja great, I have few other places to tweak ( and rebase ) probably I will wait others PR to merge, if ok for you.

Yes, ofc tyt.

**Comment by bluesign** [comment]
closing on favour of new one

**Pull request closed without merging**
