### PR TITLE
Update cadence and flow-go versions

### PR DESCRIPTION
**Pull request by SupunS**
## Description
The latest version of cadence (including transitive dependencies) is needed in the emulator for the Cadence test framework https://github.com/onflow/cadence/pull/1827, which I'm working on.
______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to GitHub issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-emulator/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation
- [x] Re-reviewed `Files changed` in the GitHub PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by sideninja** [comment]
@SupunS is this still relevant?

**Comment by SupunS** [comment]
@sideninja Yeah, this is still needed for the [test framework](https://github.com/onflow/cadence/pull/1827). I was holding this off a bit because of [this concern](https://github.com/onflow/flow-emulator/pull/177#discussion_r923662425). I'll update this PR with the cadence tag, once its created, and then this should be ready to go.

**Comment by sideninja** [comment]
Ok no worries, just doing house-keeping @SupunS

**Comment by turbolent** [comment]
@SupunS Sorry, didn't realize you had already opened this PR, but got the update done in #194, so this PR can be closed now I think

**Comment by SupunS** [comment]
That's fine. I would need to bump the versions again, after merging the new cadence stdlib. I'll open a separate PR for that anyway.

**Pull request closed without merging**
